// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bytebase/bytebase/backend/store (interfaces: UserReader,UserWriter,UserStore,ProjectReader,ProjectWriter,PlanReader,IssueReader,DatabaseReader,InstanceReader,PolicyReader,SettingReader,WorkspaceReader,AuditLogWriter,DBSchemaReader,SheetReader,RoleReader,ChangelogReader,DataStore)
//
// Generated by this command:
//
//	mockgen -package mock -destination mock_store.go github.com/bytebase/bytebase/backend/store UserReader,UserWriter,UserStore,ProjectReader,ProjectWriter,PlanReader,IssueReader,DatabaseReader,InstanceReader,PolicyReader,SettingReader,WorkspaceReader,AuditLogWriter,DBSchemaReader,SheetReader,RoleReader,ChangelogReader,DataStore
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	store "github.com/bytebase/bytebase/backend/generated-go/store"
	store0 "github.com/bytebase/bytebase/backend/store"
	model "github.com/bytebase/bytebase/backend/store/model"
	gomock "go.uber.org/mock/gomock"
)

// MockUserReader is a mock of UserReader interface.
type MockUserReader struct {
	ctrl     *gomock.Controller
	recorder *MockUserReaderMockRecorder
	isgomock struct{}
}

// MockUserReaderMockRecorder is the mock recorder for MockUserReader.
type MockUserReaderMockRecorder struct {
	mock *MockUserReader
}

// NewMockUserReader creates a new mock instance.
func NewMockUserReader(ctrl *gomock.Controller) *MockUserReader {
	mock := &MockUserReader{ctrl: ctrl}
	mock.recorder = &MockUserReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserReader) EXPECT() *MockUserReaderMockRecorder {
	return m.recorder
}

// BatchGetUsersByEmails mocks base method.
func (m *MockUserReader) BatchGetUsersByEmails(ctx context.Context, workspace string, emails []string) ([]*store0.UserMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGetUsersByEmails", ctx, workspace, emails)
	ret0, _ := ret[0].([]*store0.UserMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetUsersByEmails indicates an expected call of BatchGetUsersByEmails.
func (mr *MockUserReaderMockRecorder) BatchGetUsersByEmails(ctx, workspace, emails any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetUsersByEmails", reflect.TypeOf((*MockUserReader)(nil).BatchGetUsersByEmails), ctx, workspace, emails)
}

// GetUserByEmail mocks base method.
func (m *MockUserReader) GetUserByEmail(ctx context.Context, email string) (*store0.UserMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*store0.UserMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockUserReaderMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockUserReader)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockUserReader) GetUserByID(ctx context.Context, id int) (*store0.UserMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*store0.UserMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserReaderMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserReader)(nil).GetUserByID), ctx, id)
}

// ListUsers mocks base method.
func (m *MockUserReader) ListUsers(ctx context.Context, find *store0.FindUserMessage) ([]*store0.UserMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, find)
	ret0, _ := ret[0].([]*store0.UserMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockUserReaderMockRecorder) ListUsers(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockUserReader)(nil).ListUsers), ctx, find)
}

// MockUserWriter is a mock of UserWriter interface.
type MockUserWriter struct {
	ctrl     *gomock.Controller
	recorder *MockUserWriterMockRecorder
	isgomock struct{}
}

// MockUserWriterMockRecorder is the mock recorder for MockUserWriter.
type MockUserWriterMockRecorder struct {
	mock *MockUserWriter
}

// NewMockUserWriter creates a new mock instance.
func NewMockUserWriter(ctrl *gomock.Controller) *MockUserWriter {
	mock := &MockUserWriter{ctrl: ctrl}
	mock.recorder = &MockUserWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserWriter) EXPECT() *MockUserWriterMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserWriter) CreateUser(ctx context.Context, create *store0.UserMessage) (*store0.UserMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, create)
	ret0, _ := ret[0].(*store0.UserMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserWriterMockRecorder) CreateUser(ctx, create any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserWriter)(nil).CreateUser), ctx, create)
}

// UpdateUser mocks base method.
func (m *MockUserWriter) UpdateUser(ctx context.Context, currentUser *store0.UserMessage, patch *store0.UpdateUserMessage) (*store0.UserMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, currentUser, patch)
	ret0, _ := ret[0].(*store0.UserMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserWriterMockRecorder) UpdateUser(ctx, currentUser, patch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserWriter)(nil).UpdateUser), ctx, currentUser, patch)
}

// UpdateUserEmail mocks base method.
func (m *MockUserWriter) UpdateUserEmail(ctx context.Context, user *store0.UserMessage, newEmail string) (*store0.UserMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserEmail", ctx, user, newEmail)
	ret0, _ := ret[0].(*store0.UserMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserEmail indicates an expected call of UpdateUserEmail.
func (mr *MockUserWriterMockRecorder) UpdateUserEmail(ctx, user, newEmail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserEmail", reflect.TypeOf((*MockUserWriter)(nil).UpdateUserEmail), ctx, user, newEmail)
}

// MockUserStore is a mock of UserStore interface.
type MockUserStore struct {
	ctrl     *gomock.Controller
	recorder *MockUserStoreMockRecorder
	isgomock struct{}
}

// MockUserStoreMockRecorder is the mock recorder for MockUserStore.
type MockUserStoreMockRecorder struct {
	mock *MockUserStore
}

// NewMockUserStore creates a new mock instance.
func NewMockUserStore(ctrl *gomock.Controller) *MockUserStore {
	mock := &MockUserStore{ctrl: ctrl}
	mock.recorder = &MockUserStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserStore) EXPECT() *MockUserStoreMockRecorder {
	return m.recorder
}

// BatchGetUsersByEmails mocks base method.
func (m *MockUserStore) BatchGetUsersByEmails(ctx context.Context, workspace string, emails []string) ([]*store0.UserMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGetUsersByEmails", ctx, workspace, emails)
	ret0, _ := ret[0].([]*store0.UserMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetUsersByEmails indicates an expected call of BatchGetUsersByEmails.
func (mr *MockUserStoreMockRecorder) BatchGetUsersByEmails(ctx, workspace, emails any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetUsersByEmails", reflect.TypeOf((*MockUserStore)(nil).BatchGetUsersByEmails), ctx, workspace, emails)
}

// CreateUser mocks base method.
func (m *MockUserStore) CreateUser(ctx context.Context, create *store0.UserMessage) (*store0.UserMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, create)
	ret0, _ := ret[0].(*store0.UserMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserStoreMockRecorder) CreateUser(ctx, create any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserStore)(nil).CreateUser), ctx, create)
}

// GetUserByEmail mocks base method.
func (m *MockUserStore) GetUserByEmail(ctx context.Context, email string) (*store0.UserMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*store0.UserMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockUserStoreMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockUserStore)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockUserStore) GetUserByID(ctx context.Context, id int) (*store0.UserMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*store0.UserMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserStoreMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserStore)(nil).GetUserByID), ctx, id)
}

// ListUsers mocks base method.
func (m *MockUserStore) ListUsers(ctx context.Context, find *store0.FindUserMessage) ([]*store0.UserMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, find)
	ret0, _ := ret[0].([]*store0.UserMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockUserStoreMockRecorder) ListUsers(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockUserStore)(nil).ListUsers), ctx, find)
}

// UpdateUser mocks base method.
func (m *MockUserStore) UpdateUser(ctx context.Context, currentUser *store0.UserMessage, patch *store0.UpdateUserMessage) (*store0.UserMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, currentUser, patch)
	ret0, _ := ret[0].(*store0.UserMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserStoreMockRecorder) UpdateUser(ctx, currentUser, patch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserStore)(nil).UpdateUser), ctx, currentUser, patch)
}

// UpdateUserEmail mocks base method.
func (m *MockUserStore) UpdateUserEmail(ctx context.Context, user *store0.UserMessage, newEmail string) (*store0.UserMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserEmail", ctx, user, newEmail)
	ret0, _ := ret[0].(*store0.UserMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserEmail indicates an expected call of UpdateUserEmail.
func (mr *MockUserStoreMockRecorder) UpdateUserEmail(ctx, user, newEmail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserEmail", reflect.TypeOf((*MockUserStore)(nil).UpdateUserEmail), ctx, user, newEmail)
}

// MockProjectReader is a mock of ProjectReader interface.
type MockProjectReader struct {
	ctrl     *gomock.Controller
	recorder *MockProjectReaderMockRecorder
	isgomock struct{}
}

// MockProjectReaderMockRecorder is the mock recorder for MockProjectReader.
type MockProjectReaderMockRecorder struct {
	mock *MockProjectReader
}

// NewMockProjectReader creates a new mock instance.
func NewMockProjectReader(ctrl *gomock.Controller) *MockProjectReader {
	mock := &MockProjectReader{ctrl: ctrl}
	mock.recorder = &MockProjectReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectReader) EXPECT() *MockProjectReaderMockRecorder {
	return m.recorder
}

// GetDefaultProjectID mocks base method.
func (m *MockProjectReader) GetDefaultProjectID(ctx context.Context, workspace string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultProjectID", ctx, workspace)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefaultProjectID indicates an expected call of GetDefaultProjectID.
func (mr *MockProjectReaderMockRecorder) GetDefaultProjectID(ctx, workspace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultProjectID", reflect.TypeOf((*MockProjectReader)(nil).GetDefaultProjectID), ctx, workspace)
}

// GetProject mocks base method.
func (m *MockProjectReader) GetProject(ctx context.Context, find *store0.FindProjectMessage) (*store0.ProjectMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProject", ctx, find)
	ret0, _ := ret[0].(*store0.ProjectMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProject indicates an expected call of GetProject.
func (mr *MockProjectReaderMockRecorder) GetProject(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProject", reflect.TypeOf((*MockProjectReader)(nil).GetProject), ctx, find)
}

// ListProjects mocks base method.
func (m *MockProjectReader) ListProjects(ctx context.Context, find *store0.FindProjectMessage) ([]*store0.ProjectMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjects", ctx, find)
	ret0, _ := ret[0].([]*store0.ProjectMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjects indicates an expected call of ListProjects.
func (mr *MockProjectReaderMockRecorder) ListProjects(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjects", reflect.TypeOf((*MockProjectReader)(nil).ListProjects), ctx, find)
}

// MockProjectWriter is a mock of ProjectWriter interface.
type MockProjectWriter struct {
	ctrl     *gomock.Controller
	recorder *MockProjectWriterMockRecorder
	isgomock struct{}
}

// MockProjectWriterMockRecorder is the mock recorder for MockProjectWriter.
type MockProjectWriterMockRecorder struct {
	mock *MockProjectWriter
}

// NewMockProjectWriter creates a new mock instance.
func NewMockProjectWriter(ctrl *gomock.Controller) *MockProjectWriter {
	mock := &MockProjectWriter{ctrl: ctrl}
	mock.recorder = &MockProjectWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectWriter) EXPECT() *MockProjectWriterMockRecorder {
	return m.recorder
}

// CreateProject mocks base method.
func (m *MockProjectWriter) CreateProject(ctx context.Context, create *store0.ProjectMessage, creator *store0.UserMessage) (*store0.ProjectMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProject", ctx, create, creator)
	ret0, _ := ret[0].(*store0.ProjectMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProject indicates an expected call of CreateProject.
func (mr *MockProjectWriterMockRecorder) CreateProject(ctx, create, creator any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProject", reflect.TypeOf((*MockProjectWriter)(nil).CreateProject), ctx, create, creator)
}

// MockPlanReader is a mock of PlanReader interface.
type MockPlanReader struct {
	ctrl     *gomock.Controller
	recorder *MockPlanReaderMockRecorder
	isgomock struct{}
}

// MockPlanReaderMockRecorder is the mock recorder for MockPlanReader.
type MockPlanReaderMockRecorder struct {
	mock *MockPlanReader
}

// NewMockPlanReader creates a new mock instance.
func NewMockPlanReader(ctrl *gomock.Controller) *MockPlanReader {
	mock := &MockPlanReader{ctrl: ctrl}
	mock.recorder = &MockPlanReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlanReader) EXPECT() *MockPlanReaderMockRecorder {
	return m.recorder
}

// CreatePlan mocks base method.
func (m *MockPlanReader) CreatePlan(ctx context.Context, plan *store0.PlanMessage, creator string) (*store0.PlanMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePlan", ctx, plan, creator)
	ret0, _ := ret[0].(*store0.PlanMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePlan indicates an expected call of CreatePlan.
func (mr *MockPlanReaderMockRecorder) CreatePlan(ctx, plan, creator any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePlan", reflect.TypeOf((*MockPlanReader)(nil).CreatePlan), ctx, plan, creator)
}

// ListPlans mocks base method.
func (m *MockPlanReader) ListPlans(ctx context.Context, find *store0.FindPlanMessage) ([]*store0.PlanMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPlans", ctx, find)
	ret0, _ := ret[0].([]*store0.PlanMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPlans indicates an expected call of ListPlans.
func (mr *MockPlanReaderMockRecorder) ListPlans(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPlans", reflect.TypeOf((*MockPlanReader)(nil).ListPlans), ctx, find)
}

// MockIssueReader is a mock of IssueReader interface.
type MockIssueReader struct {
	ctrl     *gomock.Controller
	recorder *MockIssueReaderMockRecorder
	isgomock struct{}
}

// MockIssueReaderMockRecorder is the mock recorder for MockIssueReader.
type MockIssueReaderMockRecorder struct {
	mock *MockIssueReader
}

// NewMockIssueReader creates a new mock instance.
func NewMockIssueReader(ctrl *gomock.Controller) *MockIssueReader {
	mock := &MockIssueReader{ctrl: ctrl}
	mock.recorder = &MockIssueReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIssueReader) EXPECT() *MockIssueReaderMockRecorder {
	return m.recorder
}

// CreateIssue mocks base method.
func (m *MockIssueReader) CreateIssue(ctx context.Context, create *store0.IssueMessage) (*store0.IssueMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIssue", ctx, create)
	ret0, _ := ret[0].(*store0.IssueMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIssue indicates an expected call of CreateIssue.
func (mr *MockIssueReaderMockRecorder) CreateIssue(ctx, create any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIssue", reflect.TypeOf((*MockIssueReader)(nil).CreateIssue), ctx, create)
}

// GetIssue mocks base method.
func (m *MockIssueReader) GetIssue(ctx context.Context, find *store0.FindIssueMessage) (*store0.IssueMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIssue", ctx, find)
	ret0, _ := ret[0].(*store0.IssueMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIssue indicates an expected call of GetIssue.
func (mr *MockIssueReaderMockRecorder) GetIssue(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIssue", reflect.TypeOf((*MockIssueReader)(nil).GetIssue), ctx, find)
}

// ListIssues mocks base method.
func (m *MockIssueReader) ListIssues(ctx context.Context, find *store0.FindIssueMessage) ([]*store0.IssueMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIssues", ctx, find)
	ret0, _ := ret[0].([]*store0.IssueMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIssues indicates an expected call of ListIssues.
func (mr *MockIssueReaderMockRecorder) ListIssues(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIssues", reflect.TypeOf((*MockIssueReader)(nil).ListIssues), ctx, find)
}

// MockDatabaseReader is a mock of DatabaseReader interface.
type MockDatabaseReader struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseReaderMockRecorder
	isgomock struct{}
}

// MockDatabaseReaderMockRecorder is the mock recorder for MockDatabaseReader.
type MockDatabaseReaderMockRecorder struct {
	mock *MockDatabaseReader
}

// NewMockDatabaseReader creates a new mock instance.
func NewMockDatabaseReader(ctrl *gomock.Controller) *MockDatabaseReader {
	mock := &MockDatabaseReader{ctrl: ctrl}
	mock.recorder = &MockDatabaseReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabaseReader) EXPECT() *MockDatabaseReaderMockRecorder {
	return m.recorder
}

// GetDatabase mocks base method.
func (m *MockDatabaseReader) GetDatabase(ctx context.Context, find *store0.FindDatabaseMessage) (*store0.DatabaseMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatabase", ctx, find)
	ret0, _ := ret[0].(*store0.DatabaseMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDatabase indicates an expected call of GetDatabase.
func (mr *MockDatabaseReaderMockRecorder) GetDatabase(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabase", reflect.TypeOf((*MockDatabaseReader)(nil).GetDatabase), ctx, find)
}

// ListDatabases mocks base method.
func (m *MockDatabaseReader) ListDatabases(ctx context.Context, find *store0.FindDatabaseMessage) ([]*store0.DatabaseMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDatabases", ctx, find)
	ret0, _ := ret[0].([]*store0.DatabaseMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDatabases indicates an expected call of ListDatabases.
func (mr *MockDatabaseReaderMockRecorder) ListDatabases(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDatabases", reflect.TypeOf((*MockDatabaseReader)(nil).ListDatabases), ctx, find)
}

// MockInstanceReader is a mock of InstanceReader interface.
type MockInstanceReader struct {
	ctrl     *gomock.Controller
	recorder *MockInstanceReaderMockRecorder
	isgomock struct{}
}

// MockInstanceReaderMockRecorder is the mock recorder for MockInstanceReader.
type MockInstanceReaderMockRecorder struct {
	mock *MockInstanceReader
}

// NewMockInstanceReader creates a new mock instance.
func NewMockInstanceReader(ctrl *gomock.Controller) *MockInstanceReader {
	mock := &MockInstanceReader{ctrl: ctrl}
	mock.recorder = &MockInstanceReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInstanceReader) EXPECT() *MockInstanceReaderMockRecorder {
	return m.recorder
}

// CreateInstance mocks base method.
func (m *MockInstanceReader) CreateInstance(ctx context.Context, instanceCreate *store0.InstanceMessage) (*store0.InstanceMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInstance", ctx, instanceCreate)
	ret0, _ := ret[0].(*store0.InstanceMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInstance indicates an expected call of CreateInstance.
func (mr *MockInstanceReaderMockRecorder) CreateInstance(ctx, instanceCreate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInstance", reflect.TypeOf((*MockInstanceReader)(nil).CreateInstance), ctx, instanceCreate)
}

// GetInstance mocks base method.
func (m *MockInstanceReader) GetInstance(ctx context.Context, find *store0.FindInstanceMessage) (*store0.InstanceMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstance", ctx, find)
	ret0, _ := ret[0].(*store0.InstanceMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstance indicates an expected call of GetInstance.
func (mr *MockInstanceReaderMockRecorder) GetInstance(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstance", reflect.TypeOf((*MockInstanceReader)(nil).GetInstance), ctx, find)
}

// ListInstances mocks base method.
func (m *MockInstanceReader) ListInstances(ctx context.Context, find *store0.FindInstanceMessage) ([]*store0.InstanceMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInstances", ctx, find)
	ret0, _ := ret[0].([]*store0.InstanceMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInstances indicates an expected call of ListInstances.
func (mr *MockInstanceReaderMockRecorder) ListInstances(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstances", reflect.TypeOf((*MockInstanceReader)(nil).ListInstances), ctx, find)
}

// MockPolicyReader is a mock of PolicyReader interface.
type MockPolicyReader struct {
	ctrl     *gomock.Controller
	recorder *MockPolicyReaderMockRecorder
	isgomock struct{}
}

// MockPolicyReaderMockRecorder is the mock recorder for MockPolicyReader.
type MockPolicyReaderMockRecorder struct {
	mock *MockPolicyReader
}

// NewMockPolicyReader creates a new mock instance.
func NewMockPolicyReader(ctrl *gomock.Controller) *MockPolicyReader {
	mock := &MockPolicyReader{ctrl: ctrl}
	mock.recorder = &MockPolicyReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPolicyReader) EXPECT() *MockPolicyReaderMockRecorder {
	return m.recorder
}

// GetPolicy mocks base method.
func (m *MockPolicyReader) GetPolicy(ctx context.Context, find *store0.FindPolicyMessage) (*store0.PolicyMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPolicy", ctx, find)
	ret0, _ := ret[0].(*store0.PolicyMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPolicy indicates an expected call of GetPolicy.
func (mr *MockPolicyReaderMockRecorder) GetPolicy(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPolicy", reflect.TypeOf((*MockPolicyReader)(nil).GetPolicy), ctx, find)
}

// GetProjectIamPolicy mocks base method.
func (m *MockPolicyReader) GetProjectIamPolicy(ctx context.Context, workspaceID, projectID string) (*store0.IamPolicyMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectIamPolicy", ctx, workspaceID, projectID)
	ret0, _ := ret[0].(*store0.IamPolicyMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectIamPolicy indicates an expected call of GetProjectIamPolicy.
func (mr *MockPolicyReaderMockRecorder) GetProjectIamPolicy(ctx, workspaceID, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectIamPolicy", reflect.TypeOf((*MockPolicyReader)(nil).GetProjectIamPolicy), ctx, workspaceID, projectID)
}

// GetRolloutPolicy mocks base method.
func (m *MockPolicyReader) GetRolloutPolicy(ctx context.Context, workspaceID, environment string) (*store.RolloutPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRolloutPolicy", ctx, workspaceID, environment)
	ret0, _ := ret[0].(*store.RolloutPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRolloutPolicy indicates an expected call of GetRolloutPolicy.
func (mr *MockPolicyReaderMockRecorder) GetRolloutPolicy(ctx, workspaceID, environment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRolloutPolicy", reflect.TypeOf((*MockPolicyReader)(nil).GetRolloutPolicy), ctx, workspaceID, environment)
}

// GetWorkspaceIamPolicy mocks base method.
func (m *MockPolicyReader) GetWorkspaceIamPolicy(ctx context.Context, workspaceID string) (*store0.IamPolicyMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceIamPolicy", ctx, workspaceID)
	ret0, _ := ret[0].(*store0.IamPolicyMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceIamPolicy indicates an expected call of GetWorkspaceIamPolicy.
func (mr *MockPolicyReaderMockRecorder) GetWorkspaceIamPolicy(ctx, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceIamPolicy", reflect.TypeOf((*MockPolicyReader)(nil).GetWorkspaceIamPolicy), ctx, workspaceID)
}

// ListPolicies mocks base method.
func (m *MockPolicyReader) ListPolicies(ctx context.Context, find *store0.FindPolicyMessage) ([]*store0.PolicyMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPolicies", ctx, find)
	ret0, _ := ret[0].([]*store0.PolicyMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPolicies indicates an expected call of ListPolicies.
func (mr *MockPolicyReaderMockRecorder) ListPolicies(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPolicies", reflect.TypeOf((*MockPolicyReader)(nil).ListPolicies), ctx, find)
}

// MockSettingReader is a mock of SettingReader interface.
type MockSettingReader struct {
	ctrl     *gomock.Controller
	recorder *MockSettingReaderMockRecorder
	isgomock struct{}
}

// MockSettingReaderMockRecorder is the mock recorder for MockSettingReader.
type MockSettingReaderMockRecorder struct {
	mock *MockSettingReader
}

// NewMockSettingReader creates a new mock instance.
func NewMockSettingReader(ctrl *gomock.Controller) *MockSettingReader {
	mock := &MockSettingReader{ctrl: ctrl}
	mock.recorder = &MockSettingReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettingReader) EXPECT() *MockSettingReaderMockRecorder {
	return m.recorder
}

// GetSetting mocks base method.
func (m *MockSettingReader) GetSetting(ctx context.Context, workspace string, name store.SettingName) (*store0.SettingMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSetting", ctx, workspace, name)
	ret0, _ := ret[0].(*store0.SettingMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSetting indicates an expected call of GetSetting.
func (mr *MockSettingReaderMockRecorder) GetSetting(ctx, workspace, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSetting", reflect.TypeOf((*MockSettingReader)(nil).GetSetting), ctx, workspace, name)
}

// GetWorkspaceProfileSetting mocks base method.
func (m *MockSettingReader) GetWorkspaceProfileSetting(ctx context.Context, workspaceID string) (*store.WorkspaceProfileSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceProfileSetting", ctx, workspaceID)
	ret0, _ := ret[0].(*store.WorkspaceProfileSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceProfileSetting indicates an expected call of GetWorkspaceProfileSetting.
func (mr *MockSettingReaderMockRecorder) GetWorkspaceProfileSetting(ctx, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceProfileSetting", reflect.TypeOf((*MockSettingReader)(nil).GetWorkspaceProfileSetting), ctx, workspaceID)
}

// ListSettings mocks base method.
func (m *MockSettingReader) ListSettings(ctx context.Context, find *store0.FindSettingMessage) ([]*store0.SettingMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSettings", ctx, find)
	ret0, _ := ret[0].([]*store0.SettingMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSettings indicates an expected call of ListSettings.
func (mr *MockSettingReaderMockRecorder) ListSettings(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSettings", reflect.TypeOf((*MockSettingReader)(nil).ListSettings), ctx, find)
}

// MockWorkspaceReader is a mock of WorkspaceReader interface.
type MockWorkspaceReader struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspaceReaderMockRecorder
	isgomock struct{}
}

// MockWorkspaceReaderMockRecorder is the mock recorder for MockWorkspaceReader.
type MockWorkspaceReaderMockRecorder struct {
	mock *MockWorkspaceReader
}

// NewMockWorkspaceReader creates a new mock instance.
func NewMockWorkspaceReader(ctrl *gomock.Controller) *MockWorkspaceReader {
	mock := &MockWorkspaceReader{ctrl: ctrl}
	mock.recorder = &MockWorkspaceReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkspaceReader) EXPECT() *MockWorkspaceReaderMockRecorder {
	return m.recorder
}

// GetWorkspaceByID mocks base method.
func (m *MockWorkspaceReader) GetWorkspaceByID(ctx context.Context, resourceID string) (*store0.WorkspaceMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceByID", ctx, resourceID)
	ret0, _ := ret[0].(*store0.WorkspaceMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceByID indicates an expected call of GetWorkspaceByID.
func (mr *MockWorkspaceReaderMockRecorder) GetWorkspaceByID(ctx, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceByID", reflect.TypeOf((*MockWorkspaceReader)(nil).GetWorkspaceByID), ctx, resourceID)
}

// GetWorkspaceID mocks base method.
func (m *MockWorkspaceReader) GetWorkspaceID(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceID", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceID indicates an expected call of GetWorkspaceID.
func (mr *MockWorkspaceReaderMockRecorder) GetWorkspaceID(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceID", reflect.TypeOf((*MockWorkspaceReader)(nil).GetWorkspaceID), ctx)
}

// MockAuditLogWriter is a mock of AuditLogWriter interface.
type MockAuditLogWriter struct {
	ctrl     *gomock.Controller
	recorder *MockAuditLogWriterMockRecorder
	isgomock struct{}
}

// MockAuditLogWriterMockRecorder is the mock recorder for MockAuditLogWriter.
type MockAuditLogWriterMockRecorder struct {
	mock *MockAuditLogWriter
}

// NewMockAuditLogWriter creates a new mock instance.
func NewMockAuditLogWriter(ctrl *gomock.Controller) *MockAuditLogWriter {
	mock := &MockAuditLogWriter{ctrl: ctrl}
	mock.recorder = &MockAuditLogWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditLogWriter) EXPECT() *MockAuditLogWriterMockRecorder {
	return m.recorder
}

// CreateAuditLog mocks base method.
func (m *MockAuditLogWriter) CreateAuditLog(ctx context.Context, workspace string, payload *store.AuditLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAuditLog", ctx, workspace, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAuditLog indicates an expected call of CreateAuditLog.
func (mr *MockAuditLogWriterMockRecorder) CreateAuditLog(ctx, workspace, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAuditLog", reflect.TypeOf((*MockAuditLogWriter)(nil).CreateAuditLog), ctx, workspace, payload)
}

// MockDBSchemaReader is a mock of DBSchemaReader interface.
type MockDBSchemaReader struct {
	ctrl     *gomock.Controller
	recorder *MockDBSchemaReaderMockRecorder
	isgomock struct{}
}

// MockDBSchemaReaderMockRecorder is the mock recorder for MockDBSchemaReader.
type MockDBSchemaReaderMockRecorder struct {
	mock *MockDBSchemaReader
}

// NewMockDBSchemaReader creates a new mock instance.
func NewMockDBSchemaReader(ctrl *gomock.Controller) *MockDBSchemaReader {
	mock := &MockDBSchemaReader{ctrl: ctrl}
	mock.recorder = &MockDBSchemaReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBSchemaReader) EXPECT() *MockDBSchemaReaderMockRecorder {
	return m.recorder
}

// GetDBSchema mocks base method.
func (m *MockDBSchemaReader) GetDBSchema(ctx context.Context, find *store0.FindDBSchemaMessage) (*model.DatabaseMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDBSchema", ctx, find)
	ret0, _ := ret[0].(*model.DatabaseMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDBSchema indicates an expected call of GetDBSchema.
func (mr *MockDBSchemaReaderMockRecorder) GetDBSchema(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDBSchema", reflect.TypeOf((*MockDBSchemaReader)(nil).GetDBSchema), ctx, find)
}

// MockSheetReader is a mock of SheetReader interface.
type MockSheetReader struct {
	ctrl     *gomock.Controller
	recorder *MockSheetReaderMockRecorder
	isgomock struct{}
}

// MockSheetReaderMockRecorder is the mock recorder for MockSheetReader.
type MockSheetReaderMockRecorder struct {
	mock *MockSheetReader
}

// NewMockSheetReader creates a new mock instance.
func NewMockSheetReader(ctrl *gomock.Controller) *MockSheetReader {
	mock := &MockSheetReader{ctrl: ctrl}
	mock.recorder = &MockSheetReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSheetReader) EXPECT() *MockSheetReaderMockRecorder {
	return m.recorder
}

// CreateSheets mocks base method.
func (m *MockSheetReader) CreateSheets(ctx context.Context, creates ...*store0.SheetMessage) ([]*store0.SheetMessage, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range creates {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateSheets", varargs...)
	ret0, _ := ret[0].([]*store0.SheetMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSheets indicates an expected call of CreateSheets.
func (mr *MockSheetReaderMockRecorder) CreateSheets(ctx any, creates ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, creates...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSheets", reflect.TypeOf((*MockSheetReader)(nil).CreateSheets), varargs...)
}

// GetSheetFull mocks base method.
func (m *MockSheetReader) GetSheetFull(ctx context.Context, sha256Hex string) (*store0.SheetMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSheetFull", ctx, sha256Hex)
	ret0, _ := ret[0].(*store0.SheetMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSheetFull indicates an expected call of GetSheetFull.
func (mr *MockSheetReaderMockRecorder) GetSheetFull(ctx, sha256Hex any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSheetFull", reflect.TypeOf((*MockSheetReader)(nil).GetSheetFull), ctx, sha256Hex)
}

// GetSheetTruncated mocks base method.
func (m *MockSheetReader) GetSheetTruncated(ctx context.Context, sha256Hex string) (*store0.SheetMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSheetTruncated", ctx, sha256Hex)
	ret0, _ := ret[0].(*store0.SheetMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSheetTruncated indicates an expected call of GetSheetTruncated.
func (mr *MockSheetReaderMockRecorder) GetSheetTruncated(ctx, sha256Hex any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSheetTruncated", reflect.TypeOf((*MockSheetReader)(nil).GetSheetTruncated), ctx, sha256Hex)
}

// MockRoleReader is a mock of RoleReader interface.
type MockRoleReader struct {
	ctrl     *gomock.Controller
	recorder *MockRoleReaderMockRecorder
	isgomock struct{}
}

// MockRoleReaderMockRecorder is the mock recorder for MockRoleReader.
type MockRoleReaderMockRecorder struct {
	mock *MockRoleReader
}

// NewMockRoleReader creates a new mock instance.
func NewMockRoleReader(ctrl *gomock.Controller) *MockRoleReader {
	mock := &MockRoleReader{ctrl: ctrl}
	mock.recorder = &MockRoleReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleReader) EXPECT() *MockRoleReaderMockRecorder {
	return m.recorder
}

// GetRole mocks base method.
func (m *MockRoleReader) GetRole(ctx context.Context, find *store0.FindRoleMessage) (*store0.RoleMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRole", ctx, find)
	ret0, _ := ret[0].(*store0.RoleMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRole indicates an expected call of GetRole.
func (mr *MockRoleReaderMockRecorder) GetRole(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRole", reflect.TypeOf((*MockRoleReader)(nil).GetRole), ctx, find)
}

// ListRoles mocks base method.
func (m *MockRoleReader) ListRoles(ctx context.Context, find *store0.FindRoleMessage) ([]*store0.RoleMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoles", ctx, find)
	ret0, _ := ret[0].([]*store0.RoleMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoles indicates an expected call of ListRoles.
func (mr *MockRoleReaderMockRecorder) ListRoles(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoles", reflect.TypeOf((*MockRoleReader)(nil).ListRoles), ctx, find)
}

// MockChangelogReader is a mock of ChangelogReader interface.
type MockChangelogReader struct {
	ctrl     *gomock.Controller
	recorder *MockChangelogReaderMockRecorder
	isgomock struct{}
}

// MockChangelogReaderMockRecorder is the mock recorder for MockChangelogReader.
type MockChangelogReaderMockRecorder struct {
	mock *MockChangelogReader
}

// NewMockChangelogReader creates a new mock instance.
func NewMockChangelogReader(ctrl *gomock.Controller) *MockChangelogReader {
	mock := &MockChangelogReader{ctrl: ctrl}
	mock.recorder = &MockChangelogReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChangelogReader) EXPECT() *MockChangelogReaderMockRecorder {
	return m.recorder
}

// GetChangelog mocks base method.
func (m *MockChangelogReader) GetChangelog(ctx context.Context, find *store0.FindChangelogMessage) (*store0.ChangelogMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChangelog", ctx, find)
	ret0, _ := ret[0].(*store0.ChangelogMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChangelog indicates an expected call of GetChangelog.
func (mr *MockChangelogReaderMockRecorder) GetChangelog(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChangelog", reflect.TypeOf((*MockChangelogReader)(nil).GetChangelog), ctx, find)
}

// ListChangelogs mocks base method.
func (m *MockChangelogReader) ListChangelogs(ctx context.Context, find *store0.FindChangelogMessage) ([]*store0.ChangelogMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChangelogs", ctx, find)
	ret0, _ := ret[0].([]*store0.ChangelogMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChangelogs indicates an expected call of ListChangelogs.
func (mr *MockChangelogReaderMockRecorder) ListChangelogs(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChangelogs", reflect.TypeOf((*MockChangelogReader)(nil).ListChangelogs), ctx, find)
}

// MockDataStore is a mock of DataStore interface.
type MockDataStore struct {
	ctrl     *gomock.Controller
	recorder *MockDataStoreMockRecorder
	isgomock struct{}
}

// MockDataStoreMockRecorder is the mock recorder for MockDataStore.
type MockDataStoreMockRecorder struct {
	mock *MockDataStore
}

// NewMockDataStore creates a new mock instance.
func NewMockDataStore(ctrl *gomock.Controller) *MockDataStore {
	mock := &MockDataStore{ctrl: ctrl}
	mock.recorder = &MockDataStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataStore) EXPECT() *MockDataStoreMockRecorder {
	return m.recorder
}

// BatchGetUsersByEmails mocks base method.
func (m *MockDataStore) BatchGetUsersByEmails(ctx context.Context, workspace string, emails []string) ([]*store0.UserMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGetUsersByEmails", ctx, workspace, emails)
	ret0, _ := ret[0].([]*store0.UserMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetUsersByEmails indicates an expected call of BatchGetUsersByEmails.
func (mr *MockDataStoreMockRecorder) BatchGetUsersByEmails(ctx, workspace, emails any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetUsersByEmails", reflect.TypeOf((*MockDataStore)(nil).BatchGetUsersByEmails), ctx, workspace, emails)
}

// Close mocks base method.
func (m *MockDataStore) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDataStoreMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDataStore)(nil).Close))
}

// CreateAuditLog mocks base method.
func (m *MockDataStore) CreateAuditLog(ctx context.Context, workspace string, payload *store.AuditLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAuditLog", ctx, workspace, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAuditLog indicates an expected call of CreateAuditLog.
func (mr *MockDataStoreMockRecorder) CreateAuditLog(ctx, workspace, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAuditLog", reflect.TypeOf((*MockDataStore)(nil).CreateAuditLog), ctx, workspace, payload)
}

// CreateInstance mocks base method.
func (m *MockDataStore) CreateInstance(ctx context.Context, instanceCreate *store0.InstanceMessage) (*store0.InstanceMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInstance", ctx, instanceCreate)
	ret0, _ := ret[0].(*store0.InstanceMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInstance indicates an expected call of CreateInstance.
func (mr *MockDataStoreMockRecorder) CreateInstance(ctx, instanceCreate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInstance", reflect.TypeOf((*MockDataStore)(nil).CreateInstance), ctx, instanceCreate)
}

// CreateIssue mocks base method.
func (m *MockDataStore) CreateIssue(ctx context.Context, create *store0.IssueMessage) (*store0.IssueMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIssue", ctx, create)
	ret0, _ := ret[0].(*store0.IssueMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIssue indicates an expected call of CreateIssue.
func (mr *MockDataStoreMockRecorder) CreateIssue(ctx, create any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIssue", reflect.TypeOf((*MockDataStore)(nil).CreateIssue), ctx, create)
}

// CreatePlan mocks base method.
func (m *MockDataStore) CreatePlan(ctx context.Context, plan *store0.PlanMessage, creator string) (*store0.PlanMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePlan", ctx, plan, creator)
	ret0, _ := ret[0].(*store0.PlanMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePlan indicates an expected call of CreatePlan.
func (mr *MockDataStoreMockRecorder) CreatePlan(ctx, plan, creator any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePlan", reflect.TypeOf((*MockDataStore)(nil).CreatePlan), ctx, plan, creator)
}

// CreateProject mocks base method.
func (m *MockDataStore) CreateProject(ctx context.Context, create *store0.ProjectMessage, creator *store0.UserMessage) (*store0.ProjectMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProject", ctx, create, creator)
	ret0, _ := ret[0].(*store0.ProjectMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProject indicates an expected call of CreateProject.
func (mr *MockDataStoreMockRecorder) CreateProject(ctx, create, creator any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProject", reflect.TypeOf((*MockDataStore)(nil).CreateProject), ctx, create, creator)
}

// CreateSheets mocks base method.
func (m *MockDataStore) CreateSheets(ctx context.Context, creates ...*store0.SheetMessage) ([]*store0.SheetMessage, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range creates {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateSheets", varargs...)
	ret0, _ := ret[0].([]*store0.SheetMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSheets indicates an expected call of CreateSheets.
func (mr *MockDataStoreMockRecorder) CreateSheets(ctx any, creates ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, creates...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSheets", reflect.TypeOf((*MockDataStore)(nil).CreateSheets), varargs...)
}

// CreateUser mocks base method.
func (m *MockDataStore) CreateUser(ctx context.Context, create *store0.UserMessage) (*store0.UserMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, create)
	ret0, _ := ret[0].(*store0.UserMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockDataStoreMockRecorder) CreateUser(ctx, create any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockDataStore)(nil).CreateUser), ctx, create)
}

// DeleteCache mocks base method.
func (m *MockDataStore) DeleteCache() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteCache")
}

// DeleteCache indicates an expected call of DeleteCache.
func (mr *MockDataStoreMockRecorder) DeleteCache() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCache", reflect.TypeOf((*MockDataStore)(nil).DeleteCache))
}

// GetChangelog mocks base method.
func (m *MockDataStore) GetChangelog(ctx context.Context, find *store0.FindChangelogMessage) (*store0.ChangelogMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChangelog", ctx, find)
	ret0, _ := ret[0].(*store0.ChangelogMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChangelog indicates an expected call of GetChangelog.
func (mr *MockDataStoreMockRecorder) GetChangelog(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChangelog", reflect.TypeOf((*MockDataStore)(nil).GetChangelog), ctx, find)
}

// GetDB mocks base method.
func (m *MockDataStore) GetDB() *sql.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDB")
	ret0, _ := ret[0].(*sql.DB)
	return ret0
}

// GetDB indicates an expected call of GetDB.
func (mr *MockDataStoreMockRecorder) GetDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*MockDataStore)(nil).GetDB))
}

// GetDBSchema mocks base method.
func (m *MockDataStore) GetDBSchema(ctx context.Context, find *store0.FindDBSchemaMessage) (*model.DatabaseMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDBSchema", ctx, find)
	ret0, _ := ret[0].(*model.DatabaseMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDBSchema indicates an expected call of GetDBSchema.
func (mr *MockDataStoreMockRecorder) GetDBSchema(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDBSchema", reflect.TypeOf((*MockDataStore)(nil).GetDBSchema), ctx, find)
}

// GetDatabase mocks base method.
func (m *MockDataStore) GetDatabase(ctx context.Context, find *store0.FindDatabaseMessage) (*store0.DatabaseMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatabase", ctx, find)
	ret0, _ := ret[0].(*store0.DatabaseMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDatabase indicates an expected call of GetDatabase.
func (mr *MockDataStoreMockRecorder) GetDatabase(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabase", reflect.TypeOf((*MockDataStore)(nil).GetDatabase), ctx, find)
}

// GetDefaultProjectID mocks base method.
func (m *MockDataStore) GetDefaultProjectID(ctx context.Context, workspace string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultProjectID", ctx, workspace)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefaultProjectID indicates an expected call of GetDefaultProjectID.
func (mr *MockDataStoreMockRecorder) GetDefaultProjectID(ctx, workspace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultProjectID", reflect.TypeOf((*MockDataStore)(nil).GetDefaultProjectID), ctx, workspace)
}

// GetInstance mocks base method.
func (m *MockDataStore) GetInstance(ctx context.Context, find *store0.FindInstanceMessage) (*store0.InstanceMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstance", ctx, find)
	ret0, _ := ret[0].(*store0.InstanceMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstance indicates an expected call of GetInstance.
func (mr *MockDataStoreMockRecorder) GetInstance(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstance", reflect.TypeOf((*MockDataStore)(nil).GetInstance), ctx, find)
}

// GetIssue mocks base method.
func (m *MockDataStore) GetIssue(ctx context.Context, find *store0.FindIssueMessage) (*store0.IssueMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIssue", ctx, find)
	ret0, _ := ret[0].(*store0.IssueMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIssue indicates an expected call of GetIssue.
func (mr *MockDataStoreMockRecorder) GetIssue(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIssue", reflect.TypeOf((*MockDataStore)(nil).GetIssue), ctx, find)
}

// GetPolicy mocks base method.
func (m *MockDataStore) GetPolicy(ctx context.Context, find *store0.FindPolicyMessage) (*store0.PolicyMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPolicy", ctx, find)
	ret0, _ := ret[0].(*store0.PolicyMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPolicy indicates an expected call of GetPolicy.
func (mr *MockDataStoreMockRecorder) GetPolicy(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPolicy", reflect.TypeOf((*MockDataStore)(nil).GetPolicy), ctx, find)
}

// GetProject mocks base method.
func (m *MockDataStore) GetProject(ctx context.Context, find *store0.FindProjectMessage) (*store0.ProjectMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProject", ctx, find)
	ret0, _ := ret[0].(*store0.ProjectMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProject indicates an expected call of GetProject.
func (mr *MockDataStoreMockRecorder) GetProject(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProject", reflect.TypeOf((*MockDataStore)(nil).GetProject), ctx, find)
}

// GetProjectIamPolicy mocks base method.
func (m *MockDataStore) GetProjectIamPolicy(ctx context.Context, workspaceID, projectID string) (*store0.IamPolicyMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectIamPolicy", ctx, workspaceID, projectID)
	ret0, _ := ret[0].(*store0.IamPolicyMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectIamPolicy indicates an expected call of GetProjectIamPolicy.
func (mr *MockDataStoreMockRecorder) GetProjectIamPolicy(ctx, workspaceID, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectIamPolicy", reflect.TypeOf((*MockDataStore)(nil).GetProjectIamPolicy), ctx, workspaceID, projectID)
}

// GetRole mocks base method.
func (m *MockDataStore) GetRole(ctx context.Context, find *store0.FindRoleMessage) (*store0.RoleMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRole", ctx, find)
	ret0, _ := ret[0].(*store0.RoleMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRole indicates an expected call of GetRole.
func (mr *MockDataStoreMockRecorder) GetRole(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRole", reflect.TypeOf((*MockDataStore)(nil).GetRole), ctx, find)
}

// GetRolloutPolicy mocks base method.
func (m *MockDataStore) GetRolloutPolicy(ctx context.Context, workspaceID, environment string) (*store.RolloutPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRolloutPolicy", ctx, workspaceID, environment)
	ret0, _ := ret[0].(*store.RolloutPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRolloutPolicy indicates an expected call of GetRolloutPolicy.
func (mr *MockDataStoreMockRecorder) GetRolloutPolicy(ctx, workspaceID, environment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRolloutPolicy", reflect.TypeOf((*MockDataStore)(nil).GetRolloutPolicy), ctx, workspaceID, environment)
}

// GetSetting mocks base method.
func (m *MockDataStore) GetSetting(ctx context.Context, workspace string, name store.SettingName) (*store0.SettingMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSetting", ctx, workspace, name)
	ret0, _ := ret[0].(*store0.SettingMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSetting indicates an expected call of GetSetting.
func (mr *MockDataStoreMockRecorder) GetSetting(ctx, workspace, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSetting", reflect.TypeOf((*MockDataStore)(nil).GetSetting), ctx, workspace, name)
}

// GetSheetFull mocks base method.
func (m *MockDataStore) GetSheetFull(ctx context.Context, sha256Hex string) (*store0.SheetMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSheetFull", ctx, sha256Hex)
	ret0, _ := ret[0].(*store0.SheetMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSheetFull indicates an expected call of GetSheetFull.
func (mr *MockDataStoreMockRecorder) GetSheetFull(ctx, sha256Hex any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSheetFull", reflect.TypeOf((*MockDataStore)(nil).GetSheetFull), ctx, sha256Hex)
}

// GetSheetTruncated mocks base method.
func (m *MockDataStore) GetSheetTruncated(ctx context.Context, sha256Hex string) (*store0.SheetMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSheetTruncated", ctx, sha256Hex)
	ret0, _ := ret[0].(*store0.SheetMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSheetTruncated indicates an expected call of GetSheetTruncated.
func (mr *MockDataStoreMockRecorder) GetSheetTruncated(ctx, sha256Hex any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSheetTruncated", reflect.TypeOf((*MockDataStore)(nil).GetSheetTruncated), ctx, sha256Hex)
}

// GetUserByEmail mocks base method.
func (m *MockDataStore) GetUserByEmail(ctx context.Context, email string) (*store0.UserMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*store0.UserMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockDataStoreMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockDataStore)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockDataStore) GetUserByID(ctx context.Context, id int) (*store0.UserMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*store0.UserMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockDataStoreMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockDataStore)(nil).GetUserByID), ctx, id)
}

// GetWorkspaceByID mocks base method.
func (m *MockDataStore) GetWorkspaceByID(ctx context.Context, resourceID string) (*store0.WorkspaceMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceByID", ctx, resourceID)
	ret0, _ := ret[0].(*store0.WorkspaceMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceByID indicates an expected call of GetWorkspaceByID.
func (mr *MockDataStoreMockRecorder) GetWorkspaceByID(ctx, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceByID", reflect.TypeOf((*MockDataStore)(nil).GetWorkspaceByID), ctx, resourceID)
}

// GetWorkspaceID mocks base method.
func (m *MockDataStore) GetWorkspaceID(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceID", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceID indicates an expected call of GetWorkspaceID.
func (mr *MockDataStoreMockRecorder) GetWorkspaceID(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceID", reflect.TypeOf((*MockDataStore)(nil).GetWorkspaceID), ctx)
}

// GetWorkspaceIamPolicy mocks base method.
func (m *MockDataStore) GetWorkspaceIamPolicy(ctx context.Context, workspaceID string) (*store0.IamPolicyMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceIamPolicy", ctx, workspaceID)
	ret0, _ := ret[0].(*store0.IamPolicyMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceIamPolicy indicates an expected call of GetWorkspaceIamPolicy.
func (mr *MockDataStoreMockRecorder) GetWorkspaceIamPolicy(ctx, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceIamPolicy", reflect.TypeOf((*MockDataStore)(nil).GetWorkspaceIamPolicy), ctx, workspaceID)
}

// GetWorkspaceProfileSetting mocks base method.
func (m *MockDataStore) GetWorkspaceProfileSetting(ctx context.Context, workspaceID string) (*store.WorkspaceProfileSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceProfileSetting", ctx, workspaceID)
	ret0, _ := ret[0].(*store.WorkspaceProfileSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceProfileSetting indicates an expected call of GetWorkspaceProfileSetting.
func (mr *MockDataStoreMockRecorder) GetWorkspaceProfileSetting(ctx, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceProfileSetting", reflect.TypeOf((*MockDataStore)(nil).GetWorkspaceProfileSetting), ctx, workspaceID)
}

// ListChangelogs mocks base method.
func (m *MockDataStore) ListChangelogs(ctx context.Context, find *store0.FindChangelogMessage) ([]*store0.ChangelogMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChangelogs", ctx, find)
	ret0, _ := ret[0].([]*store0.ChangelogMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChangelogs indicates an expected call of ListChangelogs.
func (mr *MockDataStoreMockRecorder) ListChangelogs(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChangelogs", reflect.TypeOf((*MockDataStore)(nil).ListChangelogs), ctx, find)
}

// ListDatabases mocks base method.
func (m *MockDataStore) ListDatabases(ctx context.Context, find *store0.FindDatabaseMessage) ([]*store0.DatabaseMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDatabases", ctx, find)
	ret0, _ := ret[0].([]*store0.DatabaseMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDatabases indicates an expected call of ListDatabases.
func (mr *MockDataStoreMockRecorder) ListDatabases(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDatabases", reflect.TypeOf((*MockDataStore)(nil).ListDatabases), ctx, find)
}

// ListInstances mocks base method.
func (m *MockDataStore) ListInstances(ctx context.Context, find *store0.FindInstanceMessage) ([]*store0.InstanceMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInstances", ctx, find)
	ret0, _ := ret[0].([]*store0.InstanceMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInstances indicates an expected call of ListInstances.
func (mr *MockDataStoreMockRecorder) ListInstances(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstances", reflect.TypeOf((*MockDataStore)(nil).ListInstances), ctx, find)
}

// ListIssues mocks base method.
func (m *MockDataStore) ListIssues(ctx context.Context, find *store0.FindIssueMessage) ([]*store0.IssueMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIssues", ctx, find)
	ret0, _ := ret[0].([]*store0.IssueMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIssues indicates an expected call of ListIssues.
func (mr *MockDataStoreMockRecorder) ListIssues(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIssues", reflect.TypeOf((*MockDataStore)(nil).ListIssues), ctx, find)
}

// ListPlans mocks base method.
func (m *MockDataStore) ListPlans(ctx context.Context, find *store0.FindPlanMessage) ([]*store0.PlanMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPlans", ctx, find)
	ret0, _ := ret[0].([]*store0.PlanMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPlans indicates an expected call of ListPlans.
func (mr *MockDataStoreMockRecorder) ListPlans(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPlans", reflect.TypeOf((*MockDataStore)(nil).ListPlans), ctx, find)
}

// ListPolicies mocks base method.
func (m *MockDataStore) ListPolicies(ctx context.Context, find *store0.FindPolicyMessage) ([]*store0.PolicyMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPolicies", ctx, find)
	ret0, _ := ret[0].([]*store0.PolicyMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPolicies indicates an expected call of ListPolicies.
func (mr *MockDataStoreMockRecorder) ListPolicies(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPolicies", reflect.TypeOf((*MockDataStore)(nil).ListPolicies), ctx, find)
}

// ListProjects mocks base method.
func (m *MockDataStore) ListProjects(ctx context.Context, find *store0.FindProjectMessage) ([]*store0.ProjectMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjects", ctx, find)
	ret0, _ := ret[0].([]*store0.ProjectMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjects indicates an expected call of ListProjects.
func (mr *MockDataStoreMockRecorder) ListProjects(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjects", reflect.TypeOf((*MockDataStore)(nil).ListProjects), ctx, find)
}

// ListRoles mocks base method.
func (m *MockDataStore) ListRoles(ctx context.Context, find *store0.FindRoleMessage) ([]*store0.RoleMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoles", ctx, find)
	ret0, _ := ret[0].([]*store0.RoleMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoles indicates an expected call of ListRoles.
func (mr *MockDataStoreMockRecorder) ListRoles(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoles", reflect.TypeOf((*MockDataStore)(nil).ListRoles), ctx, find)
}

// ListSettings mocks base method.
func (m *MockDataStore) ListSettings(ctx context.Context, find *store0.FindSettingMessage) ([]*store0.SettingMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSettings", ctx, find)
	ret0, _ := ret[0].([]*store0.SettingMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSettings indicates an expected call of ListSettings.
func (mr *MockDataStoreMockRecorder) ListSettings(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSettings", reflect.TypeOf((*MockDataStore)(nil).ListSettings), ctx, find)
}

// ListUsers mocks base method.
func (m *MockDataStore) ListUsers(ctx context.Context, find *store0.FindUserMessage) ([]*store0.UserMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, find)
	ret0, _ := ret[0].([]*store0.UserMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockDataStoreMockRecorder) ListUsers(ctx, find any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockDataStore)(nil).ListUsers), ctx, find)
}

// UpdateUser mocks base method.
func (m *MockDataStore) UpdateUser(ctx context.Context, currentUser *store0.UserMessage, patch *store0.UpdateUserMessage) (*store0.UserMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, currentUser, patch)
	ret0, _ := ret[0].(*store0.UserMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockDataStoreMockRecorder) UpdateUser(ctx, currentUser, patch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockDataStore)(nil).UpdateUser), ctx, currentUser, patch)
}

// UpdateUserEmail mocks base method.
func (m *MockDataStore) UpdateUserEmail(ctx context.Context, user *store0.UserMessage, newEmail string) (*store0.UserMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserEmail", ctx, user, newEmail)
	ret0, _ := ret[0].(*store0.UserMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserEmail indicates an expected call of UpdateUserEmail.
func (mr *MockDataStoreMockRecorder) UpdateUserEmail(ctx, user, newEmail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserEmail", reflect.TypeOf((*MockDataStore)(nil).UpdateUserEmail), ctx, user, newEmail)
}
