#!/usr/bin/env tsx
// Scans src/ directory, outputs .ai-context/MODULE_INDEX.md
// Run: pnpm generate:module-map

import { readdirSync, statSync, writeFileSync } from "fs";
import { join, relative } from "path";

interface ModuleInfo {
  path: string;
  fileCount: number;
  totalLines: number;
  primaryFiles: string[];
  framework: "react" | "vue" | "mixed" | "unknown";
}

function scanModule(dirPath: string): ModuleInfo {
  let fileCount = 0;
  let totalLines = 0;
  let reactCount = 0;
  let vueCount = 0;
  const filesBySize: { name: string; size: number }[] = [];

  function traverse(currentPath: string) {
    if (!statSync(currentPath).isDirectory()) return;
    
    const entries = readdirSync(currentPath);
    for (const entry of entries) {
      const fullPath = join(currentPath, entry);
      const stat = statSync(fullPath);
      
      if (stat.isDirectory()) {
        traverse(fullPath);
      } else if (stat.isFile() && (entry.endsWith('.ts') || entry.endsWith('.tsx') || entry.endsWith('.vue'))) {
        fileCount++;
        // Rough estimate of lines based on size (approx 50 bytes per line)
        const lines = Math.max(1, Math.floor(stat.size / 50));
        totalLines += lines;
        
        if (entry.endsWith('.tsx') || (entry.endsWith('.ts') && currentPath.includes('/react/'))) {
          reactCount++;
        } else if (entry.endsWith('.vue')) {
          vueCount++;
        }
        
        filesBySize.push({ name: relative(dirPath, fullPath), size: stat.size });
      }
    }
  }

  try {
    traverse(dirPath);
  } catch (e) {
    // Directory might not exist
  }

  // Sort by size descending
  filesBySize.sort((a, b) => b.size - a.size);
  
  let framework: ModuleInfo["framework"] = "unknown";
  if (reactCount > 0 && vueCount === 0) framework = "react";
  else if (vueCount > 0 && reactCount === 0) framework = "vue";
  else if (reactCount > 0 && vueCount > 0) framework = "mixed";

  return {
    path: dirPath,
    fileCount,
    totalLines,
    primaryFiles: filesBySize.slice(0, 3).map(f => f.name),
    framework
  };
}

const modules = [
  "src/react/pages/settings",
  "src/react/pages/project",
  "src/react/pages/auth",
  "src/react/components",
  "src/store/modules/v1",
  "src/views/sql-editor",
  "src/react/plugins/agent",
];

const infos = modules.map(scanModule);

let markdown = `# Module Index

> This file is auto-generated by \`scripts/generate-module-map.ts\`. Do not edit manually.

| Module Path | Framework | Files | ~Lines | Primary Files |
|-------------|-----------|-------|--------|---------------|
`;

for (const info of infos) {
  const primaryList = info.primaryFiles.join(", ") || "-";
  markdown += `| \`${info.path}\` | ${info.framework} | ${info.fileCount} | ${info.totalLines} | ${primaryList} |\n`;
}

writeFileSync(".ai-context/MODULE_INDEX.md", markdown);
console.log("✓ MODULE_INDEX.md updated");
