/**
 * AI SERVICE MAP — Domain → Client → Store lookup.
 * Source of truth for AI code generation.
 *
 * Import clients from `@/connect` (e.g. `import { databaseServiceClientConnect } from "@/connect"`).
 * Full proto types at `src/types/proto-es/v1/*_pb.ts` — DO NOT read those files directly.
 */

export const SERVICE_MAP = {
  database: {
    client: "databaseServiceClientConnect",
    store: "useDatabaseV1Store",
    queryHook: "useDatabase",
    protoFile: "database_service_pb",
    resourceName: "instances/{instance}/databases/{db}",
    updateMaskFields: ["labels", "environment", "project", "title"],
    methods: ["getDatabase", "listDatabases", "updateDatabase", "searchDatabases", "batchGetDatabases", "syncDatabase"],
  },
  databaseCatalog: {
    client: "databaseCatalogServiceClientConnect",
    store: null,
    queryHook: null,
    protoFile: "database_catalog_service_pb",
    resourceName: "instances/{instance}/databases/{db}/catalog",
    updateMaskFields: ["catalogConfig"],
    methods: ["getDatabaseCatalog", "updateDatabaseCatalog"],
  },
  databaseGroup: {
    client: "databaseGroupServiceClientConnect",
    store: null,
    queryHook: null,
    protoFile: "database_group_service_pb",
    resourceName: "projects/{project}/databaseGroups/{group}",
    updateMaskFields: ["expression", "multitenancy"],
    methods: ["getDatabaseGroup", "listDatabaseGroups", "createDatabaseGroup", "updateDatabaseGroup", "deleteDatabaseGroup"],
  },
  project: {
    client: "projectServiceClientConnect",
    store: "useProjectV1Store",
    queryHook: "useProject",
    protoFile: "project_service_pb",
    resourceName: "projects/{project}",
    updateMaskFields: ["title", "key", "tenantMode", "schemaChange", "dataClassificationConfigId"],
    methods: ["getProject", "listProjects", "updateProject", "getIamPolicy", "setIamPolicy"],
  },
  instance: {
    client: "instanceServiceClientConnect",
    store: "useInstanceV1Store",
    queryHook: "useInstance",
    protoFile: "instance_service_pb",
    resourceName: "instances/{instance}",
    updateMaskFields: ["title", "externalLink", "dataSources", "activation"],
    methods: ["getInstance", "listInstances", "createInstance", "updateInstance", "deleteInstance", "syncInstance"],
  },
  instanceRole: {
    client: "instanceRoleServiceClientConnect",
    store: null,
    queryHook: null,
    protoFile: "instance_role_service_pb",
    resourceName: "instances/{instance}/roles/{role}",
    updateMaskFields: [],
    methods: ["listInstanceRoles"],
  },
  issue: {
    client: "issueServiceClientConnect",
    store: "useIssueV1Store",
    queryHook: "useIssue",
    protoFile: "issue_service_pb",
    resourceName: "projects/{project}/issues/{issue}",
    updateMaskFields: ["title", "description", "subscribers", "assignee"],
    methods: ["getIssue", "listIssues", "createIssue", "updateIssue", "approveIssue", "rejectIssue", "batchUpdateIssuesStatus"],
  },
  plan: {
    client: "planServiceClientConnect",
    store: "usePlanStore",
    queryHook: "usePlan",
    protoFile: "plan_service_pb",
    resourceName: "projects/{project}/plans/{plan}",
    updateMaskFields: ["title", "description", "specs"],
    methods: ["getPlan", "listPlans", "createPlan", "updatePlan"],
  },
  rollout: {
    client: "rolloutServiceClientConnect",
    store: null,
    queryHook: "useRollout",
    protoFile: "rollout_service_pb",
    resourceName: "projects/{project}/rollouts/{rollout}",
    updateMaskFields: [],
    methods: ["getRollout", "listRollouts", "createRollout", "listStages", "listTasks", "runTasks", "batchRunTasks"],
  },
  user: {
    client: "userServiceClientConnect",
    store: "useUserStore",
    queryHook: "useUser",
    protoFile: "user_service_pb",
    resourceName: "users/{email}",
    updateMaskFields: ["title", "email", "phone", "password", "mfaEnabled"],
    methods: ["getUser", "listUsers", "createUser", "updateUser", "deleteUser"],
  },
  serviceAccount: {
    client: "serviceAccountServiceClientConnect",
    store: null,
    queryHook: null,
    protoFile: "service_account_service_pb",
    resourceName: "users/{email}",
    updateMaskFields: [],
    methods: ["listServiceAccounts", "createServiceAccount", "deleteServiceAccount"],
  },
  workloadIdentity: {
    client: "workloadIdentityServiceClientConnect",
    store: null,
    queryHook: null,
    protoFile: "workload_identity_service_pb",
    resourceName: "workloadIdentities/{id}",
    updateMaskFields: [],
    methods: ["listWorkloadIdentities", "createWorkloadIdentity", "updateWorkloadIdentity", "deleteWorkloadIdentity"],
  },
  auth: {
    client: "authServiceClientConnect",
    store: "useAuthStore",
    queryHook: null,
    protoFile: "auth_service_pb",
    resourceName: null,
    updateMaskFields: [],
    methods: ["login", "logout", "refresh", "signup", "exchangeToken", "switchWorkspace"],
  },
  setting: {
    client: "settingServiceClientConnect",
    store: "useSettingV1Store",
    queryHook: null,
    protoFile: "setting_service_pb",
    resourceName: "settings/{setting}",
    updateMaskFields: ["value"],
    methods: ["getSetting", "updateSetting", "listSettings"],
  },
  subscription: {
    client: "subscriptionServiceClientConnect",
    store: "useSubscriptionV1Store",
    queryHook: null,
    protoFile: "subscription_service_pb",
    resourceName: "subscription",
    updateMaskFields: [],
    methods: ["getSubscription", "updateSubscription"],
  },
  sql: {
    client: "sqlServiceClientConnect",
    store: null,
    queryHook: null,
    protoFile: "sql_service_pb",
    resourceName: null,
    updateMaskFields: [],
    methods: ["query", "export", "searchQueryHistories"],
  },
  sheet: {
    client: "sheetServiceClientConnect",
    store: null,
    queryHook: null,
    protoFile: "sheet_service_pb",
    resourceName: "projects/{project}/sheets/{sheet}",
    updateMaskFields: ["content", "title"],
    methods: ["getSheet", "createSheet", "updateSheet"],
  },
  worksheet: {
    client: "worksheetServiceClientConnect",
    store: null,
    queryHook: null,
    protoFile: "worksheet_service_pb",
    resourceName: "projects/{project}/worksheets/{worksheet}",
    updateMaskFields: ["title", "content", "visibility", "starred"],
    methods: ["getWorksheet", "listWorksheets", "createWorksheet", "updateWorksheet", "deleteWorksheet"],
  },
  role: {
    client: "roleServiceClientConnect",
    store: null,
    queryHook: null,
    protoFile: "role_service_pb",
    resourceName: "roles/{role}",
    updateMaskFields: ["title", "description", "permissions"],
    methods: ["listRoles", "createRole", "updateRole", "deleteRole"],
  },
  group: {
    client: "groupServiceClientConnect",
    store: "useGroupStore",
    queryHook: null,
    protoFile: "group_service_pb",
    resourceName: "groups/{email}",
    updateMaskFields: ["title", "description", "members"],
    methods: ["getGroup", "listGroups", "createGroup", "updateGroup", "deleteGroup", "batchGetGroups"],
  },
  orgPolicy: {
    client: "orgPolicyServiceClientConnect",
    store: null,
    queryHook: null,
    protoFile: "org_policy_service_pb",
    resourceName: "{parent}/policies/{policy}",
    updateMaskFields: ["payload"],
    methods: ["getPolicy", "listPolicies", "createPolicy", "updatePolicy", "deletePolicy"],
  },
  reviewConfig: {
    client: "reviewConfigServiceClientConnect",
    store: null,
    queryHook: null,
    protoFile: "review_config_service_pb",
    resourceName: "reviewConfigs/{config}",
    updateMaskFields: ["title", "rules", "enabled"],
    methods: ["getReviewConfig", "updateReviewConfig", "listReviewConfigs", "createReviewConfig", "deleteReviewConfig"],
  },
  identityProvider: {
    client: "identityProviderServiceClientConnect",
    store: null,
    queryHook: null,
    protoFile: "idp_service_pb",
    resourceName: "idps/{idp}",
    updateMaskFields: ["title", "domain", "config"],
    methods: ["getIdentityProvider", "listIdentityProviders", "createIdentityProvider", "updateIdentityProvider", "deleteIdentityProvider", "testIdentityProvider"],
  },
  auditLog: {
    client: "auditLogServiceClientConnect",
    store: null,
    queryHook: null,
    protoFile: "audit_log_service_pb",
    resourceName: null,
    updateMaskFields: [],
    methods: ["searchAuditLogs", "exportAuditLogs"],
  },
  accessGrant: {
    client: "accessGrantServiceClientConnect",
    store: null,
    queryHook: null,
    protoFile: "access_grant_service_pb",
    resourceName: "projects/{project}/accessGrants/{grant}",
    updateMaskFields: [],
    methods: ["listAccessGrants", "createAccessGrant", "revokeAccessGrant", "activateAccessGrant"],
  },
  release: {
    client: "releaseServiceClientConnect",
    store: null,
    queryHook: null,
    protoFile: "release_service_pb",
    resourceName: "projects/{project}/releases/{release}",
    updateMaskFields: [],
    methods: ["listReleases", "getRelease", "createRelease"],
  },
  revision: {
    client: "revisionServiceClientConnect",
    store: null,
    queryHook: null,
    protoFile: "revision_service_pb",
    resourceName: "instances/{instance}/databases/{db}/revisions/{revision}",
    updateMaskFields: [],
    methods: ["listRevisions", "getRevision"],
  },
  cel: {
    client: "celServiceClientConnect",
    store: null,
    queryHook: null,
    protoFile: "cel_service_pb",
    resourceName: null,
    updateMaskFields: [],
    methods: ["batchParse", "batchDeparse"],
  },
  ai: {
    client: "aiServiceClientConnect",
    store: null,
    queryHook: null,
    protoFile: "ai_service_pb",
    resourceName: null,
    updateMaskFields: [],
    methods: ["chat"],
  },
  actuator: {
    client: "actuatorServiceClientConnect",
    store: null,
    queryHook: null,
    protoFile: "actuator_service_pb",
    resourceName: null,
    updateMaskFields: [],
    methods: ["getActuatorInfo", "updateActuatorInfo", "setupSample", "deleteCache"],
  },
  workspace: {
    client: "workspaceServiceClientConnect",
    store: null,
    queryHook: null,
    protoFile: "workspace_service_pb",
    resourceName: "workspaces/{workspace}",
    updateMaskFields: [],
    methods: ["getWorkspace"],
  },
} as const;

/** Type helper: domain names */
export type ServiceDomain = keyof typeof SERVICE_MAP;
